#!/bin/bash

# Set your text editor
EDITOR=vi

# If you have NGINX installed on another location, change it here
NGINX_PATH="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"

# If you use another version of PHP change this file
PHP=php7.0-fpm

echo "Welcome to the zoo!"

new(){
    NEW_PATH="$NGINX_PATH/$1"
    cp $NGINX_PATH/default $NEW_PATH
    ln $NEW_PATH $NGINX_ENABLED/$1
    sed -i "4i 127.0.0.1   "${2}"" /etc/hosts
    $EDITOR $NEW_PATH
    sudo service nginx restart
}

laravel(){
    NEW_PATH="$NGINX_PATH/$1"
    cp $NGINX_PATH/laravel $NEW_PATH
    ln $NEW_PATH $NGINX_ENABLED/$1
    sed -i "4i 127.0.0.1   "${2}"" /etc/hosts
    $EDITOR $NEW_PATH
    sudo service nginx restart

}

laravel-create(){
    NEW_PATH="$NGINX_PATH/$1"
    cp $NGINX_PATH/laravel $NEW_PATH
    ln $NEW_PATH $NGINX_ENABLED/$1
    sed -i "4i 127.0.0.1   "${2}"" /etc/hosts
    composer create-project --prefer-dist laravel/laravel /var/www/$1
    chown -R www-data:www-data /var/www/$1
    chmod -R 775 /var/www/$1/public
    find /var/www/$1 -type f -exec chmod 644 {} \;
    find /var/www/$1 -type d -exec chmod 755 {} \;
    cd /var/www/$1
    chgrp -R www-data storage bootstrap/cache
    chmod -R ug+rwx storage bootstrap/cache
    $EDITOR $NEW_PATH
    composer update
    npm install
    sudo service nginx restart
}

delete(){
    NEW_PATH="$NGINX_PATH/$1"
    if [ -f $NEW_PATH ]; then
        rm $NEW_PATH
        rm $NGINX_ENABLED/$1
        echo "Site deleted!"

        sudo service nginx restart
    fi
    
    echo "Site doesn't exist!"
}

lemp-start(){
    sudo service mysql start
    sudo service $PHP start
    sudo service nginx start
    echo "The zoo worked and the lemp stack is ready"
}

lemp-stop(){
    sudo service mysql stop
    sudo service $PHP stop
    sudo service nginx stop
    echo "The zoo stopped the lemp stack"
}

lemp-restart(){
    sudo service mysql restart
    sudo service $PHP restart
    sudo service nginx restart
    echo "Lemp stack restarted by the animals"
}

lemp-status(){
    sudo service --status-all 2>&1 | grep mysql
    sudo service --status-all 2>&1 | grep nginx
    sudo service --status-all 2>&1 | grep $PHP
}

"$@"
